name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
       - name: List Files Before Checkout
         run: |
           pwd
           ls
      - name: checkout
        uses: actions/checkout@v1  
      - name: List Files After Checkout
        run: |
          pwd
          ls          
      - name: Simple JS Action
        id: greet1
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet1.outputs.time }}"        
