name: Actions workflow New



on: 
  schedule:
    - cron:  '5 * * * *' 



jobs:

  run-simple-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a