name: Actions workflow cron
on: 
  repository_dispatch:
    types: [build]
#  schedule:
#    - cron:  '0/5 * * * *'
jobs:
  run-simple-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a